require("dotenv").config();
const express = require("express");
const { checkToken } = require("../../utils/utils");
const { imageUpload } = require("../../utils/uploadImage");
const { createGroup, leaveGroup, getAllGroupJoin, editMember } = require("./groupController");
const router = express.Router();
router.post("/create", createGroup);
router.put("/leave/:id", leaveGroup);
router.put("/kick/:id", leaveGroup);
router.get("/getAllGroupJoin", checkToken, getAllGroupJoin);
router.put("/update/:id", checkToken, editMember);
module.exports = router;
